"""
Constantes de mensajes para el módulo de clanes
"""

# Mensajes de error - Clan Management
ERROR_CREATING_ROLE = "❌ Error al crear el rol."
ERROR_CREATING_CHANNELS = "❌ Error al crear los canales."
ERROR_CLAN_NOT_FOUND = "❌ Clan no encontrado."
ERROR_NO_CLANS = "📭 No hay clanes."
ERROR_NO_CLANS_AVAILABLE = "📭 No hay clanes disponibles."
ERROR_DELETING_CLAN = "❌ No se ha podido eliminar el clan: {error}"
ERROR_NO_CLANS_TO_DELETE = "📭 No hay clanes para eliminar."
ERROR_ROLE_ALREADY_REGISTERED = "❌ El rol {role_name} ya está registrado como clan."
ERROR_NO_MEMBERS_WITH_ROLE = "❌ No se encontraron miembros con el rol {role_name}."
ERROR_MEMBER_NO_ROLE = "❌ El miembro {member} no tiene el rol {role_name}."
ERROR_CREATING_MIGRATED_CLAN = "❌ Error al crear clan {clan_name}: {error}"
ERROR_GETTING_CLAN_AFTER_CREATE = "❌ Error: No se pudo obtener el clan después de crearlo."
ERROR_UNEXPECTED_MIGRATION = "❌ Error inesperado durante la migración: {error}"
ERROR_NO_CLANS_STATS = "📊 No hay clanes creados."
ERROR_UNEXPECTED = "❌ Error inesperado: {error}"

# Mensajes de error - Member Management
ERROR_CHANNEL_NOT_CLAN = "❌ Este canal no pertenece a ningún clan."
ERROR_NO_INVITE_PERMISSIONS = "❌ No tienes permisos para invitar miembros a este clan."
ERROR_NO_KICK_PERMISSIONS = "❌ No tienes permisos para expulsar miembros de este clan."
ERROR_NO_VIEW_MEMBERS_PERMISSIONS = "❌ No tienes permisos para ver la lista de miembros."
ERROR_CLAN_NO_MEMBERS = "👥 El clan no tiene miembros."
ERROR_USER_ALREADY_IN_CLAN = "❌ El usuario ya pertenece a un clan."
ERROR_NOT_CLAN_LEADER = "❌ No eres líder de este clan."
ERROR_CANT_KICK_SELF = "❌ No puedes expulsarte a ti mismo del clan."
ERROR_USER_NOT_IN_CLAN = "❌ El usuario no está en tu clan."
ERROR_CANT_KICK_LEADER = "❌ No puedes expulsar a otro líder del clan."
ERROR_USER_NOT_CLAN_MEMBER = "❌ El usuario no es miembro de este clan."
ERROR_KICKING_MEMBER = "❌ Error al expulsar al miembro: {error}"
ERROR_LEAVING_CLAN = "❌ Error al salir del clan: {error}"
ERROR_SENDING_MESSAGE = "❌ Error al enviar el mensaje: {error}"
ERROR_TIMEOUT_CLAN_SELECTION = "⏰ Se acabó el tiempo para seleccionar un clan"

# Mensajes de error - Channel Management
ERROR_MAX_CHANNELS_REACHED = "❌ El clan **{clan_name}** ya tiene el máximo de canales de {type} ({max_channels})."
ERROR_GETTING_SETTINGS = "❌ Error al obtener configuración: {error}"
ERROR_CLAN_ROLE_NOT_FOUND = "❌ Error: No se encontró el rol del clan."
ERROR_SAVING_CHANNEL = "❌ Error al guardar el canal: {error}"
ERROR_MEMBER_NOT_IN_CLAN = "{member} no es miembro del clan **{clan_name}**."
ERROR_MEMBER_ALREADY_LEADER = "{member} ya es líder del clan **{clan_name}**."
ERROR_MEMBER_NOT_LEADER = "{member} no es líder del clan **{clan_name}**."
ERROR_CHANNEL_NOT_IN_CLAN = "El canal {channel} no pertenece al clan **{clan_name}**."
ERROR_LAST_LEADER_CANNOT_BE_DEMOTED = "No se puede degradar al único líder del clan."
ERROR_MUST_HAVE_AT_LEAST_ONE_LEADER = "El clan debe tener al menos un líder."
ERROR_USER_NOT_IN_ANY_CLAN = "No perteneces a ningún clan."
SUCCESS_LEFT_CLAN_MESSAGE = "Has salido del clan **{clan_name}** exitosamente."
MESSAGE_SELECT_CLAN_TO_LEAVE = "Selecciona el clan del que quieres salir:"

# Mensajes de configuración
ERROR_NO_PERMISSIONS_CONFIG = "❌ No tienes permisos para usar este comando."
ERROR_NO_PARAMS_PROVIDED = "❌ Debes proporcionar al menos un parámetro para configurar."
ERROR_PARAM_MUST_BE_POSITIVE = "❌ {param_name} debe ser mayor que 0."
ERROR_GETTING_CLANS_CONFIG = "❌ Error al obtener clanes: {error}"
ERROR_NO_CLANS_TO_CONFIGURE = "❌ No hay clanes disponibles para configurar."
MESSAGE_CONFIGURE_CLAN_TITLE = "**🔧 Configurar Clan**\n\nSelecciona el clan que quieres configurar:"
ERROR_EXECUTING_ACTION = "❌ Error al ejecutar la acción: {error}"
ERROR_TIMEOUT_ACTION = "⏰ **Tiempo agotado** - Selección de clan cancelada."
ERROR_PROMOTING_MEMBER = "❌ Error al promover miembro: {error}"
ERROR_MEMBER_NOT_FOUND = "❌ El miembro especificado no se encontró en el servidor."
ERROR_DEMOTING_LEADER = "❌ Error al degradar líder: {error}"
ERROR_CHANNEL_NOT_FOUND = "❌ Canal no encontrado."
ERROR_DELETING_CHANNEL = "❌ Error al eliminar canal: {error}"
ERROR_ADDING_MEMBER = "❌ Error al añadir miembro: {error}"

# Mensajes de éxito
SUCCESS_CLAN_CREATED = "✅ Clan {nombre} creado con éxito en las categorías 📝 Texto: <#{text_category}> | 🔊 Voz: <#{voice_category}> con 👥 {max_members} miembros máximo."
SUCCESS_CLAN_DELETED = "🗑️ Clan eliminado con éxito."
SUCCESS_INVITATION_SENT = "📩 Invitación enviada a {member}."
SUCCESS_MEMBER_KICKED = "🦶 {member} ha sido expulsado del clan **{clan_name}** exitosamente."

# Mensajes informativos
MESSAGE_CLAN_INVITATION = "📩 Has sido invitado a unirte al clan **{clan_name}**."
MESSAGE_USE_CLAN_LEAVE = "❌ No puedes expulsarte a ti mismo. Usa el comando `/clan salir` en su lugar."
MESSAGE_USE_SPECIFIC_CHANNEL = "📢 Ejecuta este comando desde el canal del clan específico del que quieres expulsar al miembro."

# Títulos y descripciones de embeds
EMBED_CLAN_INFO_TITLE = "🏰 Información del clan **{clan_name}**"
EMBED_CLAN_INFO_DESCRIPTION = "📋 **Información del clan {clan_name}**."
EMBED_SELECT_CLAN_DELETE_TITLE = "🗑️ Seleccionar clan a eliminar"
EMBED_SELECT_CLAN_DELETE_DESCRIPTION = "⚠️ Selecciona el clan que deseas eliminar. **Esta acción no se puede deshacer.**"
EMBED_CLAN_MIGRATION_TITLE = "✅ Clan migrado exitosamente"
EMBED_CLAN_MIGRATION_DESCRIPTION = "🔄 El clan **{clan_name}** ha sido migrado al sistema de base de datos."
EMBED_CLAN_STATS_TITLE = "📊 Estadísticas de Clanes"
EMBED_CLAN_STATS_DESCRIPTION = "📈 Resumen general del sistema de clanes"
EMBED_CLAN_MEMBERS_TITLE = "👥 Miembros de {clan_name}"
EMBED_CLAN_MEMBERS_DESCRIPTION = "📊 Total: {member_count} miembros"

# Iconos y etiquetas comunes
ICON_ROLE = "🎭 Rol"
ICON_TEXT_CHANNEL = "💬 Canal texto"
ICON_VOICE_CHANNEL = "🔊 Canal voz"

# Campos de embeds
FIELD_ID = "🆔 ID"
FIELD_NAME = "🏷️ Nombre"
FIELD_LEADERS = "👑 Líderes"
FIELD_MEMBERS = "👥 Miembros"
FIELD_MEMBER_LIMIT = "📊 Límite de miembros"
FIELD_ROLE = ICON_ROLE
FIELD_TEXT_CHANNELS = "📝 Canales de texto"
FIELD_VOICE_CHANNELS = "🔊 Canales de voz"
FIELD_CREATION_DATE = "📅 Fecha de creación"
FIELD_TOTAL_CLANS = "📊 Total de clanes"
FIELD_LEADER = "👑 Líder"
FIELD_TOTAL_MEMBERS = "👥 Miembros totales"
FIELD_ADDED_MEMBERS = "🔧 Miembros añadidos"
FIELD_CLAN_ROLE = ICON_ROLE
FIELD_TEXT_CHANNEL = ICON_TEXT_CHANNEL
FIELD_VOICE_CHANNEL = ICON_VOICE_CHANNEL
FIELD_GENERAL_NUMBERS = "📈 Números Generales"
FIELD_LARGEST_CLAN = "🏆 Clan más Grande"
FIELD_AVERAGES = "📊 Promedios"

# Valores comunes
VALUE_NONE = "⚪ Ninguno"
VALUE_TOTAL_CLANS_AVAILABLE = "📊 {count} clanes disponibles"

# Formatos de estadísticas
STATS_GENERAL_FORMAT = "**📊 Clanes totales:** {total_clans}\n**👥 Miembros totales:** {total_members}\n**👑 Líderes totales:** {total_leaders}\n**📢 Canales totales:** {total_channels}"
STATS_LARGEST_CLAN_FORMAT = "**🏰 {clan_name}**\n👥 {member_count} miembros\n📢 {channel_count} canales"
STATS_AVERAGES_FORMAT = "**👥 Miembros por clan:** {avg_members:.1f}\n**📢 Canales por clan:** {avg_channels:.1f}"
SUCCESS_INVITATION_SENT = "📩 Invitación enviada a {member}."
SUCCESS_MEMBER_KICKED = "🦶 Se ha expulsado del clan **{clan_name}** a **{member_name}**."
SUCCESS_LEFT_CLAN = "🚪 Has salido del clan **{clan_name}** exitosamente."
SUCCESS_JOINED_CLAN = "🎉 ¡Te has unido al clan **{clan_name}** exitosamente!"
SUCCESS_CHANNEL_ADDED = "✅ Canal **{channel_name}** ({type}) añadido exitosamente al clan **{clan_name}**. Canal: {channel_mention}"
SUCCESS_MEMBER_PROMOTED = "✅ {member} ha sido promovido a líder del clan **{clan_name}** exitosamente."
SUCCESS_MEMBER_PROMOTED_WITH_ROLE_WARNING = "⚠️ {member} ha sido promovido a líder del clan **{clan_name}** en la base de datos, pero hubo un problema con los roles: {role_error}"
SUCCESS_LEADER_DEMOTED = "✅ {member} ha sido degradado de líder a miembro del clan **{clan_name}** exitosamente."
SUCCESS_LEADER_DEMOTED_WITH_ROLE_WARNING = "⚠️ {member} ha sido degradado de líder a miembro del clan **{clan_name}** en la base de datos, pero hubo un problema con los roles: {role_error}"
SUCCESS_CHANNEL_DELETED = "✅ Canal **{channel_name}** eliminado exitosamente del clan **{clan_name}**."
SUCCESS_MEMBER_ADDED = "✅ {member} ha sido añadido exitosamente al clan **{clan_name}**."

# Mensajes informativos
INFO_INVITATION_SENT_TO_USER = "Se le ha enviado la invitación al clan a **{user_name}**"
INFO_KICK_REQUEST_SENT = "Se le ha enviado la solicitud de expulsión del clan a **{user_name}**"
INFO_USER_ACCEPTED_INVITATION = "**{user_name}** ha aceptado la invitación"
INFO_USER_REJECTED_INVITATION = "**{user_name}** ha rechazado la invitación"
INFO_USER_REJECTED_KICK = "**{user_name}** ha rechazado la solicitud de expulsión del clan."
INFO_USER_JOINED_CLAN = "{user} se ha unido al clan **{clan_name}**."
INFO_USER_REJECTED_CLAN = "Has rechazado la invitación al clan **{clan_name}**."
INFO_LEAVE_REQUEST = "Has solicitado salir del clan **{clan_name}** ¿Deseas continuar?"
INFO_KICK_REQUEST = "Has solicitado la expulsión del clan **{clan_name}** al miembro **{member_name}** ¿Deseas continuar?"
INFO_DIRECT_MESSAGE_ERROR = "Error al enviar el mensaje al usuario. Asegúrate de que tenga los mensajes directos habilitados."

# Mensajes de invitación
INVITATION_MESSAGE = "Te han invitado al clan **{clan_name}**"
INVITATION_CLAN_MESSAGE = "Has sido invitado a unirte al clan **{clan_name}**."

# Labels y títulos para embeds
TITLE_CLAN_INFO = "Información del clan **{clan_name}**"
TITLE_CLAN_DESCRIPTION = "**Información del clan {clan_name}**."
TITLE_MIGRATION_SUCCESS = "✅ Clan migrado exitosamente"
TITLE_MIGRATION_DESCRIPTION = "El clan **{clan_name}** ha sido migrado al sistema de base de datos."
TITLE_CLAN_STATS = "📊 Estadísticas de Clanes"
TITLE_CLAN_STATS_DESCRIPTION = "Resumen general del sistema de clanes"
TITLE_DELETE_CLAN_SELECT = "🗑️ Seleccionar clan a eliminar"
TITLE_DELETE_CLAN_DESCRIPTION = "Selecciona el clan que deseas eliminar. **Esta acción no se puede deshacer.**"
TITLE_SELECT_CLAN_ADD_CHANNEL = "🔧 Seleccionar clan para añadir canal"
DESCRIPTION_SELECT_CLAN_ADD_CHANNEL = "Selecciona el clan al que quieres añadir el canal:"
TITLE_SELECT_CLAN_ADD_LEADER = "👑 Seleccionar clan para añadir líder"
DESCRIPTION_SELECT_CLAN_ADD_LEADER = "Selecciona el clan al que quieres añadir a {member} como líder:"
TITLE_SELECT_CLAN_REMOVE_LEADER = "👑 Seleccionar clan para quitar líder"
DESCRIPTION_SELECT_CLAN_REMOVE_LEADER = "Selecciona el clan del que quieres quitar a {member} como líder:"
TITLE_SELECT_CLAN_REMOVE_CHANNEL = "🗑️ Seleccionar clan para quitar canal"
DESCRIPTION_SELECT_CLAN_REMOVE_CHANNEL = "Selecciona el clan del que quieres quitar el canal {channel}:"
TITLE_SELECT_CLAN_VIEW_MEMBERS = "👥 Seleccionar clan para ver miembros"
DESCRIPTION_SELECT_CLAN_VIEW_MEMBERS = "Selecciona el clan del que quieres ver la lista de miembros:"
TITLE_SELECT_CLAN_ADD_MEMBER = "➕ Seleccionar clan para añadir miembro"
DESCRIPTION_SELECT_CLAN_ADD_MEMBER = "Selecciona el clan al que quieres añadir a {member}:"

# Fields para embeds
FIELD_ID = "ID"
FIELD_NAME = "Nombre"
FIELD_LEADERS = "Líderes"
FIELD_MEMBERS = "Miembros"
FIELD_MEMBER_LIMIT = "Límite de miembros"
FIELD_ROLE = "Rol"
FIELD_TEXT_CHANNELS = "Canales de texto"
FIELD_VOICE_CHANNELS = "Canales de voz"
FIELD_CREATION_DATE = "Fecha de creación"
FIELD_LEADER = "👑 Líder"
FIELD_TOTAL_MEMBERS = "👥 Miembros totales"
FIELD_ADDED_MEMBERS = "🔧 Miembros añadidos"
FIELD_CLAN_ROLE = "🎭 Rol"
FIELD_TEXT_CHANNEL = "💬 Canal texto"
FIELD_VOICE_CHANNEL = "🔊 Canal voz"
FIELD_GENERAL_NUMBERS = "📈 Números Generales"
FIELD_LARGEST_CLAN = "🏆 Clan más Grande"
FIELD_AVERAGES = "📊 Promedios"
FIELD_TOTAL_CLANS = "📊 Total de clanes"

# Valores para embeds
VALUE_NONE = "Ninguno"
VALUE_TOTAL_CLANS_COUNT = "{count} clanes disponibles"
VALUE_TEXT_CHANNELS_COUNT = "{channels} ({current}/{max})"
VALUE_VOICE_CHANNELS_COUNT = "{channels} ({current}/{max})"
VALUE_GENERAL_STATS = "**Clanes totales:** {total_clans}\n**Miembros totales:** {total_members}\n**Líderes totales:** {total_leaders}\n**Canales totales:** {total_channels}"
VALUE_LARGEST_CLAN_INFO = "**{clan_name}**\n{member_count} miembros\n{channel_count} canales"
VALUE_AVERAGES_INFO = "**Miembros por clan:** {avg_members:.1f}\n**Canales por clan:** {avg_channels:.1f}"

# Descripciones de comandos
COMMAND_CREATE_CLAN_DESC = "🏗️ Crear un nuevo clan"
COMMAND_INFO_CLAN_DESC = "ℹ️ Información de un clan"
COMMAND_DELETE_CLAN_DESC = "🗑️ Eliminar un clan"
COMMAND_MIGRATE_CLAN_DESC = "🔄 Migrar un clan existente al sistema de base de datos"
COMMAND_STATS_CLAN_DESC = "📊 Ver estadísticas generales de los clanes"
COMMAND_INVITE_DESC = "📩 Invitar un miembro al clan"
COMMAND_KICK_DESC = "🦶 Expulsar un miembro del clan"
COMMAND_LEAVE_DESC = "🚪 Salir del clan"
COMMAND_JOIN_DESC = "🎯 Unirse a un clan"
COMMAND_MEMBERS_DESC = "👥 Ver la lista de miembros del clan"
COMMAND_CLAN_INFO_DESC = "ℹ️ Ver información del clan"
COMMAND_CONFIG_DESC = "⚙️ Configurar opciones del clan"
COMMAND_ADD_CHANNEL_DESC = "➕ Añadir canal adicional al clan"
COMMAND_ADD_LEADER_DESC = "👑 Promover miembro a líder"
COMMAND_REMOVE_LEADER_DESC = "⬇️ Degradar líder a miembro"
COMMAND_REMOVE_CHANNEL_DESC = "🗑️ Eliminar canal del clan"

# Descripciones de parámetros
PARAM_CLAN_NAME_DESC = "🏷️ Nombre del clan"
PARAM_LEADER_DESC = "👑 Líder del clan"
PARAM_CLAN_ID_DESC = "🆔 Id del clan"
PARAM_CLAN_ID_OPTIONAL_DESC = "🆔 Id del clan (opcional - sin especificar muestra lista para elegir)"
PARAM_PERSISTENT_DESC = "📌 Si la respuesta debe ser visible para todos (opcional, por defecto falso)"
PARAM_ROLE_DESC = ICON_ROLE + " del clan a migrar"
PARAM_TEXT_CHANNEL_DESC = "📝 Canal de texto del clan"
PARAM_VOICE_CHANNEL_DESC = "🔊 Canal de voz del clan"
PARAM_LEADER_OPTIONAL_DESC = "👑 Líder del clan (si no se especifica se toma el primer miembro con el rol)"
PARAM_MEMBER_DESC = "👤 Miembro a invitar al clan"
PARAM_MEMBER_KICK_DESC = "🦶 Miembro a expulsar del clan"
PARAM_CLAN_NAME_JOIN_DESC = "🏷️ Nombre del clan al que quieres unirte"

# Nombres de grupos de comandos
GROUP_LEADER = "lider"
GROUP_LEADER_DESC = "👑 Comandos para líderes de clan"
GROUP_MOD = "mod"
GROUP_MOD_DESC = "🛡️ Comandos de moderación de clanes"

# Mensajes de confirmación
CONFIRM_LEAVE_CLAN = "❓ ¿Estás seguro de que quieres salir del clan **{clan_name}**?"
CONFIRM_KICK_MEMBER = "❓ ¿Estás seguro de que quieres expulsar a **{member_name}** del clan **{clan_name}**?"
